### PR TITLE
Update for locust 1.4.1

### PR DESCRIPTION
**Pull request by FutureSharks**
Resolves https://github.com/FutureSharks/invokust/issues/45

- Update references to `num_clients` and `hatch_rate` as these have been removed in locust
- Rerun and fixed the examples from the README
- Fix a warning from pytest
- Add CI for running tests in Github
- Add test for running a very simple load test

### CODE REVIEW

**Comment by FutureSharks** [comment]
@CsilLAB do you know why the tests fail when running in Github actions? I think it's something to do with `zope.interface` package in `Pipfile`?

**Comment by CsilLAB** [comment]
Probably. I am happy too look over the weekend, feel free to merge this and I'll take a look later.

**Comment by FutureSharks** [comment]
@CsilLAB, never mind, I got it sorted 🙂

**Comment by CsilLAB** [comment]
@FutureSharks Sorry I did not get back to you over the last weekend. Thanks for updating the test. Happy holidays. :)

**Pull request merged**
