### PR TITLE
Locust v0.9.0 parity 

### PR DESCRIPTION
**Pull request by HughZurname**
Hoping to use this for a project and noticed that there has been some drift from the main locust version (see #21). 

This seems to have been addressed on the KanoComputing/shorthorn fork, but as there is no outstanding PR. 

I figured it would be nice to get these merged in and up on Pypi if you're okay with that @FutureSharks?

### CODE REVIEW

**Comment by FutureSharks** [comment]
I'm definitely OK with that! Thanks @HughZurname.

I'll test, merge and release this in the next day or so.

**Comment by FutureSharks** [comment]
Hey @HughZurname I did a quick test and the example in the readme doesn't work. e.g.

```python
import invokust

settings = invokust.create_settings(
    locustfile='locustfile_example.py',
    host='http://example.com',
    num_clients=1,
    hatch_rate=1,
    )

loadtest = invokust.LocustLoadTest(settings)
loadtest.run()
```

Adding `run_time='20s'` didn't help either. Does it work for you?

**Comment by HughZurname** [comment]
Hey @FutureSharks, thanks for looking into it 😁

Yeah, you're right 😢 I'll have a look and see if I can get it running today and let you know. I think the property may have a different name. I'll let you know what I find 👍

**Comment by HughZurname** [comment]
> Hey @FutureSharks, thanks for looking into it 😁
> 
> Yeah, you're right 😢 I'll have a look and see if I can get it running today and let you know. I think the property may have a different name. I'll let you know what I find 👍

So it looks like the way it's been done here is to pass the timeout directly into the `run()` method here https://github.com/FutureSharks/invokust/blob/907bb6b83918d384c38beafb8f57e2dc81f9cb58/invokust/loadtest.py#L78-L91 

Testing it with:

```python
import invokust

settings = invokust.create_settings(
    locustfile='locustfile_example.py',
    host='http://example.com',
    num_clients=1,
    hatch_rate=1,
    # run_time='3s'
    )

loadtest = invokust.LocustLoadTest(settings)
loadtest.run('3s')
loadtest.stats()
```
Seems to achieve the desired effect, but IMO I think it should take the value from the settings object for consistencies sake. I can roll the changes of this PR into another one where it implements it using settings you like?

**Comment by FutureSharks** [comment]
>  I can roll the changes of this PR into another one where it implements it using settings you like?

Sure, sounds great!

**Comment by FutureSharks** [comment]
Or we merge this, you make a small PR after and then I can tag and release? Up to you.

**Comment by HughZurname** [comment]
> Or we merge this, you make a small PR after and then I can tag and release? Up to you.

This sounds more sensible 👍 I'll wait for the merge and do another PR 😁

**Pull request merged**
