### PR TITLE
Make compatible with locust 1.0.3

### PR DESCRIPTION
**Pull request by CsilLAB**
Issue #30
Locust has an new major version available. There is a new way to use locust as a lib.
(https://docs.locust.io/en/stable/use-as-lib.html)

Changes:
- use locust the recommended way as a lib
- updated settings and removed params that are no longer necessary
- Locust improved their terminology: clients/locusts have been renamed as users in locust, updating occurrences here.
- updated README as parameter names have changed as per the previous point
- fix bug caused by typo in invokr
- improve some error handling
- adding Pipfile to aid local development
- updated examples to bring inline with locust examples
- fix typo in setup.py keyword

I updated the version to 1.0a (as alpha), bumping major version as the invokr interface has changed.

### CODE REVIEW

**Comment by CsilLAB** [comment]
Changed to draft while resolving merge conflicts.

**Comment by CsilLAB** [comment]
I hope it's not too hard to review - let me know if you'd like me to move the smaller changes to a separate PR.

I have a bunch of ideas how to improve the code (some refactoring, adding tests, etc.). Would you mind if I sent a few PRs in the future for these?

**Comment by FutureSharks** [comment]
Hey @CsilLAB, thanks for the PRs and work! I really appreciate it. I am on holiday for 3 weeks right now and also, generally speaking, I don't have a huge amount of time for this project. So I made you a collaborator, hope that works for you 😃  So basically you can open and merge PRs as you wish. I'll still check them when I have time but don't really have time to do testing.

I think I'll add a github action to push to PyPI on tag creation. Then also the release process is automated. Sound OK?

**Comment by FutureSharks** [comment]
> Would you mind if I sent a few PRs in the future for these?

That would be great!

**Comment by CsilLAB** [comment]
Thanks, I am honoured to be a collaborator! Already accepted the invite. The github action on the project sounds great too! :) I'll raise PRs when I have time to improve the code, add tests, etc. Looking forward for the reviews when you have time. :)

Enjoy your holiday. :)

**Comment by FutureSharks** [comment]
OK I added the action in this commit: https://github.com/FutureSharks/invokust/commit/50d94b6c06153dd606b55554b4fffd7e9272c744

If it works, when you create a tag and setup.py has been updated then it should automatically publish the new package version to PyPi.

**Pull request merged**
